baseurl:
exclude: ['README.md']

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

gems:
  - jekyll-archives

jekyll-archives:
  enabled: all
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
